- name: Perform initial setup
  hosts: all
  remote_user: mgr

  tasks:
  - name: "add docker apt repo"
    ansible.builtin.script:
      cmd: "scripts/setup_docker_apt_repo.sh"
      creates: "/etc/apt/sources.list.d/docker.list"

  - name: "Install required apt packages"
    become: true
    ansible.builtin.apt:
      name: 
        - git
        - docker-ce 
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest

  - name: "Add user to docker group"
    become: true
    ansible.builtin.user:
      name: 'mgr'
      groups: docker
      append: yes

  - name: "Install zrok"
    block:
      - name: "Unarchive to a bin directory"
        become: true
        ansible.builtin.unarchive:
          src: https://github.com/openziti/zrok/releases/download/v0.4.46/zrok_0.4.46_linux_arm64.tar.gz
          remote_src: true
          dest: /usr/local/bin
          include:
            - zrok
      - name: "Update zrok exec permissions"
        become: true
        ansible.builtin.file:
          path: /usr/local/bin/zrok
          mode: '0766'
          state: file
      - name: "Enable zrok with proper key"
        no_log: true
        ansible.builtin.command:
          cmd: "/usr/local/bin/zrok enable {{ zrok_key }}"
